# Generated by Django 2.1 on 2018-08-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codefonction', models.CharField(max_length=15)),
                ('nomfonction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeadherent', models.CharField(max_length=15)),
                ('civilite', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulevieasso.Fonction')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codestructure', models.CharField(max_length=15)),
                ('nomstructure', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='individu',
            name='strucutre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulevieasso.Structure'),
        ),
    ]
