# Generated by Django 2.1 on 2018-08-18 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulevieasso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(blank=True, null=True, verbose_name='dateCreation')),
                ('lieuApl', models.CharField(max_length=100, verbose_name='lieuapl')),
                ('nbPresent', models.IntegerField(null=True, verbose_name='nbPresent')),
                ('nbVotant', models.IntegerField(null=True, verbose_name='nbVotant')),
                ('nbPour', models.IntegerField(null=True, verbose_name='nbPour')),
                ('nbContre', models.IntegerField(null=True, verbose_name='nbContre')),
                ('nbAbstention', models.IntegerField(null=True, verbose_name='nbAbstention')),
                ('budgetPresente', models.BooleanField(default=False, verbose_name='budgetPresente')),
                ('bilanFinancier', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='bilanFinancier')),
                ('corpsCr', models.CharField(blank=True, max_length=500, null=True, verbose_name='corpsCr')),
                ('signataireCr', models.CharField(blank=True, max_length=50, null=True, verbose_name='signataireCr')),
                ('valide', models.BooleanField(default=False, verbose_name='validation')),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateNomination', models.DateTimeField(verbose_name='datenomination')),
                ('commentaire', models.CharField(max_length=200)),
                ('fonction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulevieasso.Fonction')),
            ],
        ),
        migrations.RemoveField(
            model_name='individu',
            name='fonction',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='strucutre',
        ),
        migrations.AddField(
            model_name='individu',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulevieasso.Structure'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='nominant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominant', to='modulevieasso.Individu'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='delegueAg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegueag', to='modulevieasso.Individu'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='equipeanimation',
            field=models.ManyToManyField(to='modulevieasso.Individu'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='representantNational',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representantnational', to='modulevieasso.Individu'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='representantRegional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representantregional', to='modulevieasso.Individu'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='resla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resla', to='modulevieasso.Individu'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='sla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulevieasso.Structure'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='supDelegueAg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supdelegueag', to='modulevieasso.Individu'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='tresla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tresla', to='modulevieasso.Individu'),
        ),
        migrations.AddField(
            model_name='individu',
            name='nominations',
            field=models.ManyToManyField(to='modulevieasso.Nomination'),
        ),
    ]
