# Generated by Django 2.1 on 2018-09-12 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulevieasso', '0002_auto_20180818_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeNominationRedaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDemande', models.DateTimeField(null=True, verbose_name='datenomination')),
                ('dateReponse', models.DateTimeField(null=True, verbose_name='datereponse')),
                ('reponseAdmin', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('role', models.CharField(max_length=50, null=True)),
                ('mail', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=50, null=True)),
                ('codepostal', models.CharField(max_length=50, null=True)),
                ('tel', models.CharField(max_length=50, null=True)),
                ('nomination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulevieasso.DemandeNominationRedaction')),
            ],
        ),
        migrations.RemoveField(
            model_name='individu',
            name='nominations',
        ),
        migrations.AddField(
            model_name='compterendu',
            name='dateapl',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dateapl'),
        ),
        migrations.AddField(
            model_name='individu',
            name='adresse',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individu',
            name='codepostal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individu',
            name='mail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individu',
            name='nomination',
            field=models.ManyToManyField(related_name='nomination_individu', to='modulevieasso.Nomination'),
        ),
        migrations.AddField(
            model_name='individu',
            name='tel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulevieasso.Structure'),
        ),
        migrations.AlterField(
            model_name='compterendu',
            name='dateCreation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='datecreationcr'),
        ),
        migrations.AlterField(
            model_name='compterendu',
            name='lieuApl',
            field=models.CharField(max_length=100, null=True, verbose_name='lieuapl'),
        ),
        migrations.AlterField(
            model_name='compterendu',
            name='representantNational',
            field=models.CharField(max_length=100, null=True, verbose_name='representantnational'),
        ),
        migrations.AlterField(
            model_name='compterendu',
            name='representantRegional',
            field=models.CharField(max_length=100, null=True, verbose_name='representantregional'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='civilite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='individu',
            name='codeadherent',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='individu',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='individu',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='codestructure',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='nomstructure',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demandenominationredaction',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulevieasso.Structure'),
        ),
    ]
